INSERT INTO `homestead`.`straten` (`straatnaam`) VALUES ('s Meiersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) VALUES ('s-hertogenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('s-hertogenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Aarschotsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Abdij Van Park');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Abdij Vlierbeek');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Acht-meistraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Albert Woutersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Alfons Smetsplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Alfons Verbovenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Alsembergstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ambachtenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Andreas Vesaliusstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ankerstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Armand Thierylaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Arthur De Greefstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Augustijnenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bankstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Baron August De Becker Remyplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Baron D eynattenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Baron Descampslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bayostraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Benedictijnenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Berkenhoflaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bermstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bertemstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bierbeekstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Biezenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bijlokstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bleydenberglaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Blijde Inkomststraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Boekhandelstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bogaardenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bondgenotenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Boogschuttersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Boomgaardstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bornestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Borstelsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bosstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Brabanconnestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Brabantlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bremstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Broekstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Brouwerijplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Brouwersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Brouwerstraat/ Leuvensestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Brugstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Brusselsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Brusselsestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Bunswijkstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Burchtstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Burgemeester Jozef Eerdekensstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Burgemeesterstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Busleidengang');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Cardenberch');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Casablancalaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Casinolaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Celestijnenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Celestynenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Centrumstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Charles Deberiotstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Christinastraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Consciencestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Constantin Meunierstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Crabeelsweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Craenendonck');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Croylaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('D. Mellaertsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Dagobertstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Dalemhof');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('De Bayostraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('De Becker-remyplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('De Vier Vaantjes');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Dekenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Dellenhof');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Diestersteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Diestestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Diestsepoort');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Diestsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Diestsestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Diestsestraat 253/');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Diestsevest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Dieststraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Dirk Boutslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Domeinstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Dreefstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Drie Engelenberg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Drie Engelenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Drinkwaterstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Duinberglaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('E40 Luik - Brussel');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Eegveld');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Eenmeilaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Egelantierlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Egenhovenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Eikenbergstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Eikstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Emile Mathieustraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Engels Plein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Englebert Carleerlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Erasme Ruelensvest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Esperantolaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Eugeen Vanhooren Bekenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Eugene Gilbertstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Familie De Bayostraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Fazantenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Fochplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Fonteinstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Franiois Demarsinstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Franz Tielemanslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Franz-schollaertstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Frederik Laan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Frederik Lintsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Galgebergstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Gaston Eyskenslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Gaston Feremanslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Gaston Geenslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Gebroeders Tassetstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Geldenaaksebaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Geldenaaksevest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Gemeenteplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Gemeentestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Gerard Vanderlindenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Goudsbloemstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Grauwmeer');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Grensstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Groenestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Groeneweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Groenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Groenveldstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Groot Begijnhof');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Grote Markt');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Halfmaartstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hallengang');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Halvestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Heidebergstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Heilige-geeststraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hendrik Consciencestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Henri Elsenwijk');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Henri Regastraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Henricus Wittebolsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Herbert Hooverplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Herentsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Herestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hertogstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Het Torentje');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hoegaardsestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hogeschoolplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Holsbeeksesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hooverplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hovenersdreef');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hulsberg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Hungaria Vaartkom (2e Verdiep)');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ijzerenmolenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ijzerenpoortstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ijzermolenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Industrieweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Interleuvenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jachtlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jan Davidstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jan Stasstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jan Van Avondtstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jan-baptist Vanderelststraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jan-pieter Minckelersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Janseniusstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jean Bulenswijk');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jean-babtiste Van Monsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jodenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jozef Eerdekensstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jozef Ii-straat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jozef Wautersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Jules Vandenbemptlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Justus Lipsiusstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kaboutermansstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kamperfoelieweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kantineplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kapeldreef');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kapucijnenvoer');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kardinaal Mercierlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kardinaal Mercierplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kareelveld');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Karekietenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Karel Van Lotharingenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kastanjelaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kasteelpark Arenberg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Keibergstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kerkstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kesseldallaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Klaproosstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kleine Mechelsebaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kloosterbosstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Koetsweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kolonel Begaultlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Koning Albertlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Koning Leopold I-straat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Koning Leopold Iii Laan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Koning Leopold1 Straat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Korbeek-losestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Korbeekhof');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Kortestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Krakenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('La Vignette');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ladeuzeplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Landbouwstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Lange-beemdenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Langendaallaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Laurent-benoit Dewezlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leeuwerikenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Lei');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leming');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leo Dartelaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leon Schreursvest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leopold Decouxlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leopold Vanderkelenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leopold-i-straat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leuvensesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Leuvensestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Liemingenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Lijsterlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Lindensestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Lodewijk Engelbertus Van Arenbergplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Lolanden');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Louis Melsensstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Louis Woutersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Lozenhoekstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Luikstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Maarschalk Fochplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Margarethaplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Maria Van Belstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Maria-theresiastraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Martelarenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Martelarenplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Martelarenplein Z-n');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Mathieu De Layensplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Mechelsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Mechelsestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Mechelsevest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Melsensstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Mercatorpad');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Meugenslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Mezenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Mgr. Ladeuzeplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Michielsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Middelweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Minckelerstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Minderbroedersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Minderbroederstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Molenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Monseigneur Ladeuzeplein 22-');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Monseigneur Van Waeyenberghlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Monseingeur Ladeuzeplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Montinho Das Canas (algarve,portugal)');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Muntstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Mussenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Naamsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Naamsestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Naamsevest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Nachtegalenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Nieuwe Bornestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Noormannenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ondernemingenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Onze Lieve Vrouwstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Oud-heverleestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Oude Aarschotseweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Oude Baan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Oude Diestsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Oude Markt');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Oude Mechelsebaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Oude Rondelaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Oudebaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Overloopstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('P. Van Ostaijenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Panoramalaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Parijsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Parkbosstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Parkstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Pasteelsblokweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Pastoor Bellonstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Pastoor Legrandstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Pater Damiaanplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Paul Delvauxwijk');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Paul Lebrunstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Paul Van Ostaijenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Pellenbergstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Penitentienenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Pensstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Persstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Peter Benoitlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Petermannenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Peterseliegang');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Philipslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Philipssite');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Pierre Joseph Van Benedenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Platte Lostraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Pleinstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Poelstraaat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Predikherenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Prins-regentplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Prinses Lydialaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Prosper Poulletlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Puttebroekstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ramberg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Rapengang');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ravenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Redingenhof');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Redingenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Remylaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Research Park Haasrode Geldenaaksebaan, Zone 3');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Riddersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ridderstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ridersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Rijschoolstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ristweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Romeinse Straat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Romeinsestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Rooistraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Rotselaarsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Savoyestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Schapenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Schipvaartstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Schoonzichtlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Schorenhof');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Schrijnmakersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint Michielsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-annastraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-antoniusberg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-hubertusstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-jacobsplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-janbergsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-jansbergsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-lambertusstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-maartensstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-maartenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sint-reneldisplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Slachthuislaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sluisstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Spaanse Burchtlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Spaanse-kroonlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Spaarzaamheidstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Sparrendreef');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Spiegelstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('St. Jansbergsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Staatsbaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Stadsvest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Standonckstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Stapelhuisstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Stationslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Steenbakkerijstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Technologielaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Ter Boelhage');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Terbankstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Termunckstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Tervuursesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Tervuursestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Tervuursevest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Tessenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Thomas Woodrow Wilsonlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Tiensesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Tiensestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Tiensevest');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Toverberg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Trolieberg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Tweekleinewegenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vaartdijk');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vaartkom');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vaartstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Valkerijgang');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Valleistraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Van Arnbergplein');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Van Benedenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Van Der Nootstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vanbenedenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vanden Tymplestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vandenbemptlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vanderkelenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Verbindingslaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vesaliusstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vierhuizenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vilhoekstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Villapark');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vinkenbosstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vismarkt');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vital Decosterstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vlamingenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vlierbeeklaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vlietstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Volmolenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vredestraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Vuurkruisenlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wagenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wakkerzeelsebaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wandelingstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Waversebaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Weggevoerdenstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Weldadigheidsstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wielewaallaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wieringstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wijgmaalbroek');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wijgmaalsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wijngaardlaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wijnpersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Willem Coosemansstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Willem De Croylaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wilselsesteenweg');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wittebolstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Wittehoevelaan');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Zwaluwbeekstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Zwarte Zustersstraat');
INSERT INTO `homestead`.`straten` (`straatnaam`) values ('Zwarte Zusterstraat');